name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.2.3)'
        required: true
      minor:
        description: 'Minor version tag (e.g., 1.2)'
        required: true
      major:
        description: 'Major version tag (e.g., 1)'
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Bundle action
        run: bun run build
      - name: Set git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Create release commit
        run: |
          git add -f dist
          git commit -m "chore: release"
      - name: Create version tags
        run: |
          RELEASE_COMMIT=$(git rev-parse HEAD)
          git tag -af "$VERSION" "$RELEASE_COMMIT" -m "Release $VERSION"
          git tag -af "$MINOR" "$RELEASE_COMMIT" -m "$MINOR -> $VERSION"
          git tag -af "$MAJOR" "$RELEASE_COMMIT" -m "$MAJOR -> $VERSION"
          git push origin "$MINOR" "$MAJOR" --force
        env:
          MINOR: ${{ github.event.inputs.minor }}
          MAJOR: ${{ github.event.inputs.major }}